version: '3.8'
services:
  website:
    image: pashaefimchik/lab_4_website
    container_name: flask_app
    restart: always
    environment: 
      DB_HOST: sql11.freesqldatabase.com
      DB_NAME: sql11439524
      DB_USER: sql11439524
      DB_PASSWORD: KtQxsMz8W1
    depends_on:
      - db
    ports: 
      - 5000:5000

  db:
    image: mysql:latest
    container_name: flask_mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: KtQxsMz8W1
      MYSQL_PASSWORD: KtQxsMz8W1
      MYSQL_USER: sql11439524
      MYSQL_DATABASE: sql11439524
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: flask_phpmyadmin
    restart: always
    ports: 
      - 3306
    environment: 
      PMA_HOST: sql11.freesqldatabase.com
      PMA_USER: sql11439524
      PMA_PASSWORD: KtQxsMz8W1
      MYSQL_ROOT_PASSWORD: KtQxsMz8W1
